### ISSUE TITLE
Create empty Xcode project

### ISSUE THREAD

**Issue by dersim-davaod** [ios-course/ironfoudation-team-project#1]
### DoD:
- Create a project with the name  `Woof` and settings described below in the section  Project settings:
- You should set up linters in Xcode in the build phase:
   - SwiftLint  - version 0.51.0
   - SwiftFormat - version 0.51.7
- Add `.gitignore`  file. 
It should exclude files generated by macOS like `DS_Store` and generated by Xcode related to the user `xcuserdata/`.
- Add project structure. Use MVVM architecture and organize code by layers. Create 3 directories: `Model`, `View`, `ViewModel`.

#### Project settings:
- Deployment target - 15.0
- Supported devices - iPhone only
- Supported modes - portrait
- Dark/night theme - deactivate

**Comment by NadzeyaShpakouskaya** [comment]
Move the part about readme file to issue [#14](https://github.com/ios-course/ironfoudation-team-project/issues/14)

**Comment by NadzeyaShpakouskaya** [comment]
Swiftlint + swiftformat latest version,
deployment target - 15.0
supported devices  - iPhone only
supported modes  - portrait
night theme - deactivate

**Comment by NadzeyaShpakouskaya** [comment]
+ Add .gitignore file
