### ISSUE TITLE
Fix name display in pet sitter's list

### ISSUE THREAD

**Issue by julyakmita** [ios-course/ironfoudation-team-project#100]
## Depends on tasks:
- #16 

## Description
The main goal of this task is to make the display of all characters in the pet sitters' list (or make the display od the first and last name standardised).

### Dev requirements and restrictions:
Fixe line limit in the text that is displaying pet sitter's full name.

## UI Mocks
Based on the UI of the #16.

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/30
