### ISSUE TITLE
Prepare for release 0.3.0

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#107]
## Depends on tasks:
- #3 

## Description:
Prepare the documentation and source for release.

### User requirements:
User should be able to go to the release page in repo, get the information about changes that were done and be able to download/setup the app

### Dev requirements and restrictions:

- Create a new branch for the release with the name "release-0.3.0" and set it up for release;
- Create a new branch to bump the version, if requires.
- Check the CHANGELOG.md, verify that there are no missed changes, and update with release information;
- Add the necessary info to the [Release_notes](https://github.com/ios-course/ironfoudation-team-project/blob/main/release_notes.md) in a user-friendly format based on CHANGELOG.md.
- Before merging to the main branch set up the tag "v.0.3.0" on the last commit before the merge commit.
- Publish the Release under the Release [section on GitHub.](https://github.com/ios-course/ironfoudation-team-project/releases)

**Comment by julyakmita** [comment]
## 0.3.0

### New features

`Log in`: Add possibility for user to select how to run the app - as a pet owner or a pet sitter.

`Copy info`: Users are able to copy the name and the phone number of a pet sitter by  a long tapping on the sitter's full name and phone information.
