### ISSUE TITLE
Create Main TabView for pet owner

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#11]
# DoD:

Create Main TabView for pet owner

[App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

## Description

A new SwiftUI TabView needs to be created for the pet owner side of app. This TabView will serve as the main view of the app when it is launched. The TabView should be styled based on the guidelines provided in the app's wiki, which has pages dedicated to color style, font, and used images.

## Acceptance Criteria

- A new SwiftUI TabView is created with 3 tabs representing the main functionality of the PetSitter app:

1. Sitters.
2. Walkings.
3. Profile.

- The TabView should be styled based on the guidelines provided in the app's wiki, which has pages dedicated to color style, font, and used images.

- The first tab `Sitters` should display a stub view with text: "list of PetSitters":
   - **Header for navigation bar:** Find your sitter
   - **Icon for tab bar:** SFSymbols - magnifyingglass
   - **Title for tab bar:** Sitters
- The second tab should include a stub view with text: "walking":
   - **Header for navigation bar:** My walkings
   - **Icon for tab bar:** SFSymbols - pawprint.fill
   - **Title for tab bar:** Walkings
- The third tab should include a stub view with text: "pet owner info":
   - **Header for navigation bar:** My profile
   - **Icon for tab bar:** SFSymbols - person.text.rectangle.fill
   - **Title for tab bar:** Profile

The header in navigation bar displays in  `inline` mode, and should change when the tab switches.
The tint color for icon  is`Dark purple`  for the selected state, and `Dark gray` for the unselected state from [App style guide](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

**UI example**
<img width="269" alt="Screenshot 2023-04-28 at 14 12 41" src="https://user-images.githubusercontent.com/32869814/235120885-345d5f18-cc32-404e-a5f3-0aed9426233e.png">

**Comment by NadzeyaShpakouskaya** [comment]
update the description, add the ui section

**Comment by NadzeyaShpakouskaya** [comment]
Discuss info about font and size.
Add the names of icons.
Discuss the color scheme.
