### ISSUE TITLE
Refactor `KeyValueStorage.loadData()`

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#116]
## Description
Refactor method `KeyValueStorage.loadData()` to avoid potential unscheduled storages due to passing string type key

### Dev requirements and restrictions:
- current version:
``` swift
func loadData(for key: String) -> Data? {}
```
- possible version
``` swift
func loadData(for key: KeyValueStorage.Key) -> Data? {}
```

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/29
