### ISSUE TITLE
Create filters for list of sitters

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#12]
## Description

Create the view with a list of filters, where the user can set  some filters to filter the list of sitters in Sitter's tab (search sitters view):
 -  price range (min and/or max value),
 - min value for rating,
 - display or not unrated sitters.

## DoD:

1. Create a view that contains:
   - section with 2 buttons: `Save` and `Cancel` at the top of the view,
   - section with filter list described below.
  
2. Create a section with a filter list that allows you to apply the next filters:
- Price (set min, max values). You can use text fields or a dropdown menu to set values.
- Rating (set min value). Create a dropdown menu to set value.
- Display or not unrated sitters. The best option is to use a switch.

3.  If the button `Save` is pressed,  the current view dismisses, the selected filters should be applied to the list of sitters in the tab `Sitters`.
Applied filters should be saved in `UserDefaults` to be able to set up the same filters when the app will relaunch.

4. If the button `Cancel`  is pressed, the current view dismisses,  selected filters don't apply, and don't save to `UserDefaults`.

## UI Example:

You are free to choose your own design that followed [App Style Guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

**Comment by NadzeyaShpakouskaya** [comment]
Update the description.

**To discuss:**

- should we add optional filters?
- should we store the filters in user defaults or they will be reset when the app closed?

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/37
