### ISSUE TITLE
Create enum contains NetworkError

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#123]
## This task is a part of:
- #59

### Dev requirements and restrictions:
ToDo: add more error cases, discuss with team
``` swift
enum NetworkError: Error {
   case authenticationError
   case serverError
   case timeOut
   case lostConnection
   case clientError
}
```
range of errors: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by julyakmita** [comment]
``` swift
case invalidResponse
case badUrl
case decodingError
```

**Comment by julyakmita** [comment]
Issue has been closed, because it's there is the same issue in the `simple-network-service` repository to which it refers.
