### ISSUE TITLE
Create API endpoint for `WoofApp`

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#124]
## This task is part of
- #59 

## Depends on tasks:
- #121 
- https://github.com/ios-course/simple-network-service/issues/3

## Description
Create the object to describe the endpoint and requests that will be made in the app. 

### Subtasks:
 - [x] #200
 - [x] create Endpoint with obfuscated data

## DoD
Create API endpoint for `WoofApp` that conforms to `HTTPAPIEndpoint` from `NetworkServise` 

enum `Request`  will be empty for now,  new cases will be added to describe the request to the backend like described below  (examples):
   - case getAllSitters:  - GET https://woof-app.hasura.app/api/rest/pet_sitters/all
   - case addNewSitter(Sitter):    - POST https://woof-app.hasura.app/api/rest/pet_sitters/new

**Comment by kirpichonok** [comment]
Closed with PR [#199](https://github.com/ios-course/ironfoudation-team-project/pull/199).
