### ISSUE TITLE
Create detailed petSitter View

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#13]
# DoD:

Create screen Pet Sitter View

[App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

### Description

- Create a new SwiftUI view called "PetSitterProfileView" that displays the following UI elements:
    - An image view displaying the pet sitter's avatar.
    - A label displaying the pet sitter's name and surname.
    - A label displaying the pet sitter's bio information.
    - A label displaying the pet sitter's phone number (this can be temporary data).
    - A custom "rating view" that displays a number of images representing the pet sitter's rating. The number of images displayed should correspond to the pet sitter's rating out of 5, rounded to the nearest whole number.
- You are free to suggest your own design of the view but follow the [App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines).

### Subtasks

- [ ] Create ViewModel for the Detail pet sitter view;
- [ ] Create the View for the  Detail pet sitter view.

**Comment by NadzeyaShpakouskaya** [comment]
Update Dod.
I think we shouldn't display phone info for everyone, only in the walking views, when walking was booked or walking is done.
Also, maybe we should not show the booking area for 1st sprint at all.

**Comment by iBYarchitect** [comment]
Update:
- Avatar(stub)
- Name
- Surname
- Phone
- Rating

**Comment by NadzeyaShpakouskaya** [comment]
@iBYarchitect @julyakmita 
What do you think about creating a separate view for Avatar, that we can use around the app?


![Image](https://user-images.githubusercontent.com/32869814/236661422-d753b854-351f-440d-8d84-5f6719dbd21e.png)
