### ISSUE TITLE
Create `Request` object for NetworkService

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#132]
## This task is a part of:
- #122 

## Description
- Create `Request` object for NetworkService that contains next properties:
   - `URI`  of type `URL?`
   - `requestMethod`  of type `HTTPMethod`
   - `headers`  of type `HTTPHeaders`
   - `body` of type `String?`

```swift
typealias HTTPHeaders = [HTTPHeaderKey: HTTPHeaderValue]
typealias HTTPHeaderKey = String
typealias HTTPHeaderValue = String
```

- Create the enum `HTTPMethod` with the next cases for now
```swift
 enum HTTPMethod {
         case get = "GET"
         case post = "POST"
         case put = "PUT"
}
```

**Comment by kirpichonok** [comment]
The issue was replaced with  [this issue](https://github.com/ios-course/simple-network-service/issues/3)
