### ISSUE TITLE
Refactor PreferencesHandler 

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#137]
## Depends on tasks:
- #110 

## Description
Refactor the code to use the existing Preferences type instead of creating a new one as done in the current version #115 

### Dev requirements and restrictions:
- Move existing methods to structure `Preferences`

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/28
