### ISSUE TITLE
Update the SitterProfileView based on integration network layer in viewModel.

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#146]
## This task is a part of:
- #9 

## Depends on tasks:
- #61
- #114
- #133 

## Description
When the user press `Save` button and the internet connection is lost or any errors occur when the request has been sent display a pop-up window (alert message) with:

-  a hint message `Unable to save your details.`
- 2 buttons: try again(save button) and cancel (back to editing mode).

When `Try again` button is pressed the method from viewModel to send a request to the backend should be triggered.
When `Cancel` button is pressed, dismiss alert message stay on `SitterEditInfoView`.

## DoD
 - Add an alert to SitterProfileView
```swift
.alert("Unable to save your details.", isPresented: $viewModel.isErrorOccurred) {
    Button("Try again") {
      // trigger method in the view model to make a request to backend one more time
     }
     Button("Cancel") {
      // don't save any changes, switch back to edit mode
     }
}
```

## UI Mocks
<img width="218" alt="Screenshot 2023-06-12 at 21 59 40" src="https://github.com/ios-course/ironfoudation-team-project/assets/32869814/f16d9216-ee27-4a92-9d28-c2d983ae3892">

**Comment by kirpichonok** [comment]
Will it be more correct to specify in section "Depend on tasks:"  the task #133?

**Comment by kirpichonok** [comment]
How to check internet connection is lost?
We need appropriate error in the Network Service.
