### ISSUE TITLE
Use StarRating(value: Double) initializer instead of the `DataTransformer.fiveStarRating`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#150]
## Linked with task:
- #151 

## Description

Use `StarRating(value: Double)` initializer instead of the `DataTransformer.fiveStarRating`.

Issue created based on [comment](https://github.com/ios-course/ironfoudation-team-project/pull/127#discussion_r1226527804).

### Dev requirements and restrictions:

**Comment by NadzeyaShpakouskaya** [comment]
Transfer to new project https://github.com/IronFoundation/iOS-Woof/issues/26
