### ISSUE TITLE
Improve implementation of method `DataTransformer.fiveStarRating`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#151]
## Linked with task:
- #150 

## Description
Improve core logic of method `DataTransformer.fiveStarRating`:
```
Could you please explain the core logic a bit (why it works in this way)?

Why we return the unavailable case for the rating -5.5, but return the value fiveStars for the rating 10.5? Should we return unavailable if the given value > 5.0?
```
Issue created based on [comment](https://github.com/ios-course/ironfoudation-team-project/pull/127#discussion_r1226526211).

### Dev requirements and restrictions:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/27
