### ISSUE TITLE
Refactor `DetailPetSitterView` code: replace `contextMenu` with `UIEditMenuInteraction`.

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/ironfoudation-team-project#155]
## Description
The `contextMenu` method can be replaced with class `UIEditMenuInteraction`. That will provide consistent view of context menu for application views. The context menu should contain similar items for all views, but there is one item `Copy` in the context menu for `AvatarView` and `TextWithIconLabelView` at the moment.

### User story:
On a long tap on the sitter's full name label, the user sees the context menu where the action copy displays.
When the action copy is tapped, the name should be copied into the clipboard.

On a long tap on the sitter's phone number label, the user sees the context menu where the action copy displays.
When the action copy is tapped, the phone number should be copied into the clipboard.

## Other useful information
This feature implemented with `.contextMenu` method. 
The link on the class `UIEditMenuInteraction`:
https://developer.apple.com/documentation/uikit/uieditmenuinteraction

**Comment by NadzeyaShpakouskaya** [comment]
transfer to new project https://github.com/IronFoundation/iOS-Woof/issues/25
