### ISSUE TITLE
Allow pet owners to book pet sitters

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#168]
## Depends on tasks:
- #_issue

### Owner flow:
- #173
- #175
- #176
- #180
- #181
- #182
- #177
- #179
- #183
- #184
- #185

## Description
Pet owners can book the pet sitters from the list using the app (instead of calling on their own) through the feature `Request walking`.

#### Owner flow:
Now users can see in which city the sitter is located, which will allow them to choose the right sitter.

The user navigates to a page with a list of sitters, where they can select any sitter and see the specific information about that sitter by tapping on them. On the current sitter's screen, the user can tap on the "Request a walk" button.

Once they tap the button, a window should appear where the user needs to provide specific details such as the location, date, and time for the walk. After entering the information, they tap the button "Book" and the request is sent to the sitter.

In the "Walkings" tab, a new walk should appear under the "Upcoming Walks" section. The user can tap on it to view the details of that walk. If the walk is in the "Upcoming Walks" section, there should be a "Complete" button. Upon tapping it, the walk should be moved to the "Completed Walks" section.

#### Owner flow:
- create `OwnerWalkingCardView`
- create `OwnerListOfWalkingView`
- create a model for `Walking`
- create `OwnerWalkingCardViewModel`
- create `OwnerListOfWalkingViewModel`
- add the button` Request walking`  in `SitterDetailedCardView`
- create a `WalkingRequestView` to fill out a form with the date, time, and place of the walking request
- load the data about walking to the storage
- show stored walking on the `Walking` tab
- add sections `Booked` and `Completed` to the `ListOfWalkingView`
- add the button `Complete` to the `WalkingCardView`
- add logic to move completed walkings to the section `Completed` after tapping the button `Complete`

**Comment by NadzeyaShpakouskaya** [comment]
> How the sitter receives notification? (in what form? Push notification?)
As we discussed during the last meeting regarding new features, we will not use push notifications for now.
When the sitters switch to the walking tab they will see just a list with requests for walking. I like your idea with the badges in the tab bar.

**Comment by YuliaNastiushkina** [comment]
Thanks for your comments, I fixed the description.

**Comment by NadzeyaShpakouskaya** [comment]
@YuliaNastiushkina, 
We should add the backend integration as well:
- when the owner taps on the `Book` button the request to the backend should be sent to create a new walking record, not only stored in storage.
- when the sitter loads the app request to the backend to fetch all request walking should be sent, otherwise, we couldn't display the badge message if we don't that any requests exist.

So we need to discuss what should be implemented at the backend and ask Dersim to implement this before the sprint start.

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/12
