### ISSUE TITLE
Refactor login process to create and store the new instance of sitter or owner based on the selected role.

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#172]
## Description
After the user selects their role on the login screen (tapped on the button `I am an owner` or `I am a sitter`), the new instance of owner or sitter should be created and saved to persistent storage based on the selected role.

### Dev requirements and restrictions:
When the user selects `owner` role, the new instance of the owner should be created and saved to persistent storage `KeyValueStorage.Name.currentOwner` with the key `KeyValueStorage.Key.currentOwner`.

When the user selects `sitter` role, the new instance of the sitter should be created and saved to persistent storage `KeyValueStorage.Name.currentSitter` with the key `KeyValueStorage.Key.currentSitter`.

**Comment by iBYarchitect** [comment]
Is it worth describing that the default entities of the owner or sitter should be created?

**Comment by NadzeyaShpakouskaya** [comment]
@iBYarchitect  the phrase of new instance is not enough or it is not clear?

**Comment by iBYarchitect** [comment]
I would note that the new entity should be with a unique uuid, but the rest of the properties should be nil

**Comment by kirpichonok** [comment]
Use default init `Sitter()` or `Owner()` to create a new instance.
