### ISSUE TITLE
Create `OwnerWalkingCardView`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#173]
TO DISCUSS:
Do we need to add the `Finish` button to change the status of walking?

## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #_issue
- #_issue

## Description
The view with details of walking for the owner.
The view must consider the name of the sitter, place of walking, date, and time.

### User story:
Users can see the card of current walking with a preview of details.

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/13
