### ISSUE TITLE
Create `OwnerListOfWalkingView`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#175]
**TO DISCUSS:**
Do we need sections to split the walking or they will display in one list with some labels like booked/finished?
 - Booked
 - Finished

How the walkings will be sorted in the list?

## This task is a part of the issue:
 - #168 

## Description
View the list of the `OwnerWalkingCardView` to see all walks on the `Walkings` tab.

### User story:
Users can see a list of walkings on the `Walking` tab and scroll them.

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/14
