### ISSUE TITLE
Create a `WalkingRequestView`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#176]
## This task is a part of the issue:
 - #168 

## Description
The view with text fields to fill out about walking requests.

### User story:
User can fill out the information about date, time and place of walking request.

### Dev requirements and restrictions:
_**Information about sitter must be fill out automatically when the owner will open this view via `SitterCardView`**_ ?????

## UI Mocks

TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
We can fill in the address of the owner from their personal info.
We should verify that all fields are not empty/

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/15
