### ISSUE TITLE
Add the button` Request walking`  in `SitterDetailedCardView`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#177]
## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #176 

## Description
Button to create walking requests.

### User story:
Users can select a sitter and on the view of the current sitter detail (`SitterDetailedCardView`) tap the button `Request walking` to open the view `WalkingRequestView` to create the walking request.

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/19
