### ISSUE TITLE
Load the data about Walking Request to the storage

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#179]
TO DISCUSS:
 We should send a request to the backend as well to create new instance of walking on the server, that will be displayed on the sitter's side.

## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #173 
- #176 
- #177 
- #180 
- #181

## Description
Load instances `Walking` to the storage.

### User story:
Users can load data about walking to the storage by tab the button `Book` on the `SitterDetailedCardView`

### Dev requirements and restrictions:
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/20
