### ISSUE TITLE
Create model for `Walking`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#180]
## This task is a part of the issue:
 - #168 

## Description
Add model of `Walking`.
**_Should contain a walking ID, sitter ID, owner ID, place, date, and time. ??????_**
Do we need status: booked and finished for now?

### Dev requirements and restrictions:
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/16
