### ISSUE TITLE
Create `OwnerWalkingCardViewModel`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#181]
TO DISCUSS: what should be done:
1. get info about walking from storage
1. get status of walking from backend
1. change status of walking at the backend and in storage.

## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #173 

## Description
TODO:

### Dev requirements and restrictions:
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/17
