### ISSUE TITLE
Create `OwnerListOfWalkingViewModel`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#182]
TO DISCUSS:
How to get info about walkings: local storage + backend for status? or send request to backend to get and sync data from backend with local storage

## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #175 

## Description
TODO:

### Dev requirements and restrictions:
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/18
