### ISSUE TITLE
Show stored walking on the `Walking` tab

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#183]
## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #173 
- #175 
- #176 
- #180 
- #181 
- #177

## Description
When the user taps the button `Book` the current walking card must display on the `Walking` tab.
- send a request to the backend
- if successed, save to persistent storage

### User story:
TODO:

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/21
