### ISSUE TITLE
Add sections `Booked` and `Completed` to the `ListOfWalkingView

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#184]
## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #173 
- #175 
- #180 
- #181 
- #182 

## Description
On the `Walking` tab must be two sections: `Booked` and `Completed`.
How it will look?

### User story:
TODO:

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/22
