### ISSUE TITLE
Add the button `Complete` to the `WalkingCardView`

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/ironfoudation-team-project#185]
## This task is a part of the issue:
 - #168 

## Depends on tasks:
- #184 

## Description
Create button `Complete` to the `WalkingCardView`. When the user tap to this button, booked walking must move from the section "Booked" to "Completed" and display it in the `Walking` tab on the section "Completed".

### User story:
TODO:

### Dev requirements and restrictions:
TODO:

## UI Mocks
TODO:

## Other useful information
TODO:

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/23
