### ISSUE TITLE
Create Sitter Model with doc comments and without tests

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#19]
# DoD: 

Create Sitter Model with doc comments and without tests

## Description

A new model called Sitter needs to be created. The Sitter model will have the following properties:

``` swift
id: UUID
name: String
surname: String
phone: String
avatarUrl: URL?
bio: String
rating: Double
pricePerHour: Double
```

## Documentation

- Each property in the Sitter model should have doc comments explaining its purpose and data type.
- Model should conform `Codable` and `Identifiable` protocols.

**Comment by NadzeyaShpakouskaya** [comment]
Discuss architecture
Do we need doc comments and tests?

**Comment by iBYarchitect** [comment]
@NadzeyaShpakouskaya 
I read [article](https://medium.com/@vladislavshkodich/architectures-comparing-for-swiftui-6351f1fb3605) about architectures comparing for SwiftUI, and I know only MVVM design pattern. I think MVVM it's a better choice for us.
Doc comments needed.
Do we need to conform protocol?

**Comment by iBYarchitect** [comment]
@NadzeyaShpakouskaya Based on reading several articles, I would place network requests in the ViewModel layer.

> The main question for me: Do we need a verification process in a model layer or in a model view layer?

Ok, I need to think about this. The first idea that comes to mind is to create a page on a Wiki with descriptions for the different types of data used in the app.

> I'm not sure that we should specify that information in doc comments? If we decide to change the format of mobile number we should update the info in our model.

That's a good idea, but the naming of the cases is a bit confusing to me. Also, what about double-type numbers used in the rating system?

``` swift
enum Rating: Int {
        case unrated = 0
        case awful
        case bad
        case satisfied
        case good
        case outstanding
    }
```

**Comment by iBYarchitect** [comment]
@julyakmitaI added this line to answer your question:

> It is necessary to provide a placeholder for the avatar in case the user does not upload one.

**Comment by NadzeyaShpakouskaya** [comment]
Agreed to keep Rating as Double.
Remove restrictions for properties for model.
