### ISSUE TITLE
Add the new request to the WoofAppHTTPEndpoint to update the entered information to the backend.

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#207]
## This task is a part of the issue:
 - #9 

## Depends on tasks:
- Get information from the backend developer about the PUT request

## Description
Add the new request to the `WoofAppHTTPEndpoint` to update the entered information from the backend.

case addNewSitter(Sitter):    - PUT ToDo: https://woof-app.hasura.app/api/rest/pet_sitters/new

### Dev requirements and restrictions:
Add  a new case `updateSitter(Sitter)` to the extension with requests:

```swift 
enum Request { 
   // ...
   case updateSitter   
   // ...
}
```
Information for this case - PUT ToDo: https://woof-app.hasura.app/api/rest/pet_sitters/all

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new organization https://github.com/IronFoundation/iOS-Woof/issues/8
