### ISSUE TITLE
Create Pet model

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#21]
# DoD: 

Create Pet Model with doc comments and without tests

[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

## Description

ToDo: Issue for Validating pet model data.

A new model called Pet needs to be created. The Pet model'll have the following properties:

``` swift
id: UUID
ownerID: UUID
name: String
weight: Double
avatarURL: Url?
notes: String
rating: Double
```

## Documentation

- Each property in the Pet model should have doc comments explaining its purpose and data type.
- Model should conform `Codable` and `Identifiable` protocols.

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/36
