### ISSUE TITLE
Improve API of the `WoofAppEndpoint.addNewSitter`.

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/ironfoudation-team-project#215]
## Description
Do a refactor of the `WoofAppEndpoint`. Update `addNewSitter` according to the implementation at the moment of the commit a4e439af9d8. We should provide convenient and clear API and move body parameters into the implementation of the `WoofAppEndpoint` or to change the implementation of the `SimpleNetworkService`.

## DoD
API for adding a new sitter must look like: 
`.addNewSitter(Sitter)`

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new organization https://github.com/IronFoundation/iOS-Woof/issues/7
