### ISSUE TITLE
Create Pet card view for PetOwner Tab View

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#28]
# DoD:

Create Pet card view for PetOwner Tab View

[App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

## Description

This task is dependent on task #11. 
The objective is to create a pet information section for the pet owner's profile tab view. This section will include a model layer for the pet and test data for the UI, which will be saved in UserDefaults. Additionally, a view model layer will be required to transfer data from the model to the view.
The pet section will display pet information as a card with a button to add a new pet. Tapping the button will open a screen to add a new pet. Each row in the pet card is also tappable, and upon tapping, it will display a screen to edit information about the pet.

## Requirements

- The pet section should include a model layer and view model for the owner and test data for the UI.
- The data should be saved in UserDefaults.
- The pet section should display pet info as a card.
- The card view should containt more than one pet.
- The pet section should include a button for adding new pet and tapable row info about pet to edditing information about selected pet.

**Additional details:**
The pet profile card is a part of the main tab screen.

#### UI Example

![iScreen Shoter - 20230504122347152](https://user-images.githubusercontent.com/103530508/236178151-a801d41b-0d60-4ea0-a3df-ad10a83bd23c.jpg)

**Comment by NadzeyaShpakouskaya** [comment]
@iBYarchitect @julyakmita 
Some questions:
1) As I remember we agreed to use one button style (text or image). For personal information, we use the button with `Edit` text, but here it's the icon. Should we change this to be more consistent?
2) What about the icon stub, we will not allow the user to change or add the avatar for now, maybe make sense to generate an icon with the first letter of the pet name and use SF Symbol letter for that, for example for Charlie use  - `c.circle`?
3) User should be able to add and edit, what about the possibility to delete?
