### ISSUE TITLE
Create template s for PRs and Issues

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#39]
## Depends on tasks:
none

## Description
Create the templates for PRs and issues in the repo to make workflow easier.
Templates should be created in the team's GitHub repository.

### User requirements:
- Discuss with the team and agree on templates for PR and issue.
- Add the  PR template to repo.
- Add the issue template to repo.

### Dev requirements and restrictions:
- investigate where the templates should be stored and how to create them. 

## UI Mocks
not required

## Other useful information
Maybe useful to check the [Git documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

**Comment by iBYarchitect** [comment]
Looks great, I don't have any questions.

**Comment by NadzeyaShpakouskaya** [comment]
PR template

## Summary
This PR is a part of the work to resolve #_issue
....


## Changes
-
-



## Checks to complete
- [ ] I have performed a self-review of my code
- [ ] PR title is in a conventional commit style
- [ ] My code follows the style guide of the project, I build and run it, and no warnings or errors occur
- [ ] I documented my code properly
- [ ] I added tests to my work
- [ ] Existing tests pass with my changes
