### ISSUE TITLE
Create Sign In screen view

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#4]
## Depends on tasks:
- #80
- #31 

## Description
Create a view that allows a user to select how to run the app  - as a pet owner or a pet sitter.
It's a temporary view to manage 2 flows in the app (pet owner and pet sitter).

### User story:

- Create View to display two buttons for (log in as pet owner and pet sitter);
- The `I am an owner` button redirects to the main tab screen for a pet owner;
- The `I am a sitter` button redirects to the main tab screen for a pet sitter;
- Pressing on the button triggers ViewModel to save the selected role as user Preferences.

## UI Mocks
Create a screen with 2 buttons with text `I am an owner` and `I am a sitter`.
You can choose your own design based on [App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines).

**Comment by NadzeyaShpakouskaya** [comment]
Do we need the link to restore the password if the user forgot it?
