### ISSUE TITLE
Prepare information for release

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#45]
## Depends on tasks:
- #49 

## Description:
Prepare the documentation and source for release.

### User requirements:
User should be able to go to the release page in repo, get the information about changes that were done and be able to download/setup the app
//TODO: Discuss how we can provide the app to the user.

### Dev requirements and restrictions:
- Create a new branch for the release with the name "release-0.1.0" and set it up for release;
- Check the  `CHANGELOG.md`, verify that there are no missed changes, and update with release information;
- Add the necessary info to the [Release_notes](https://github.com/ios-course/ironfoudation-team-project/blob/main/release_notes.md) in a user-friendly format based on `CHANGELOG.md.`
   - Add guidelines on how to set up the application.
   - Add some screenshots, if it helps the user to understand what are the new features about.
- Before merging to the main branch set up the tag "v.0.1.0" on the last commit.

## UI Mocks
not required

## Other helpful information
none

**Comment by julyakmita** [comment]
[0.1.0] - [24.05.2023]

## Changes

### New features

### Bug Fixes

**Comment by julyakmita** [comment]
Yes, you are right. So for the `CHANGELOG.md`:

### Added 
- Add `Local storage based on user defaults` and tests for it  - [#58](https://github.com/ios-course/ironfoudation-team-project/pull/58)

**Comment by NadzeyaShpakouskaya** [comment]
@iBYarchitect  will add it to his PR by himself.
For the future, every PR should modify the changelog, and you should make changes by yourself.

**Comment by julyakmita** [comment]
**Fixed information in the README.md**

## Installation

**Pre-requisites**: 
- installed Xcode with the version specified under the [Current development Environment](#current-dev-environment).

1) in current [repository](git@github.com:ios-course/ironfoudation-team-project.git) go to the `Code` item in the horizontal menu bar.
2) in the `Release` section download `Assets` file with the archive of the required version of the application and unzip it.
3) open the file `Woof.xcodeproj` in Xcode.
4) select your device as the destination.
5) press the run button.
If you don't know how to run the app on a real device, please check the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device).

**Comment by iBYarchitect** [comment]
@julyakmita link to [Current development Environment](https://github.com/ios-course/ironfoudation-team-project/issues/45#current-dev-environment) shows current page

1. We could provide a direct link to the release with the asset to download, with an explanation for downloading the archive
2. Extract the downloaded archive and find Woof.xcodeproj
3. Open the file Woof.xcodeproj in Xcode.
4. Select your device as the destination.
5. Press the run button.
If you don't know how to run the app on a real device, please check the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device).

**Comment by NadzeyaShpakouskaya** [comment]
> We could provide a direct link to the release with the asset to download, with an explanation for downloading the archive
We can add the link to the Release page and write that users can download any specific version that they want or the latest release.
If we provide the link to the assets, we have to update the installation section in README.md for every release.

**Comment by iBYarchitect** [comment]
@NadzeyaShpakouskaya this variant looks better?
- Look for the releases section on [this page](https://github.com/ios-course/ironfoudation-team-project) in the vertical menu on the right side?
- Select the latest release(link to releases page), if necessary, or older ones by clicking on Releases
- Please select the archive format that best suits your needs and proceed with the download.
- Extract the downloaded archive and find Woof.xcodepro
- Open the file Woof.xcodeproj in Xcode.
- Select your device as the destination.
- Press the run button.
If you don't know how to run the app on a real device, please check the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device).
