### ISSUE TITLE
Create add/edit petOwner View

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#7]
## Depends on tasks:
- https://github.com/ios-course/ironfoudation-team-project/issues/11
- https://github.com/ios-course/ironfoudation-team-project/issues/20 
- https://github.com/ios-course/ironfoudation-team-project/issues/15
- https://github.com/ios-course/ironfoudation-team-project/issues/44

## Description

The goal of this task is to create a SwiftUI view allowing information about pet owner to be added or edited. The data will be saved in UserDefaults. 

### User story:
User can add information about himself and  edit it.

### Dev requirements and restrictions:
Create  a view with next UI elements:
  - Pet Owner Avatar as `image`
  - Change avatar as `button`
  - Name as  `textfield`
  - Surname as  textfield
  - Phone as `textFiled`
  - Detailed address info section with:
  - City as `textfield`
  - Street as `textfield`
  - House/apartment as `textfield`
  - Save as `button`
 Store entered information to UserDefaults and present the info in Profile View.
 Add tests 

## UI Mocks
![Image](https://user-images.githubusercontent.com/32869814/235336367-0fce5ff7-a3a6-4918-890e-99b20f041c8e.png)

## Other useful information

[App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)
[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

**Comment by NadzeyaShpakouskaya** [comment]
Update Dod + add UI example

**Comment by NadzeyaShpakouskaya** [comment]
@iBYarchitect as we discussed early, maybe we don't need this view right now if we change the personal information using text fields on Pet Owner Card View. What do you think?
