### ISSUE TITLE
Create methods in owner model to interact with persistent storage

### ISSUE THREAD

**Issue by julyakmita** [ios-course/ironfoudation-team-project#74]
## Depends on tasks:
- #44 

## Description
Create methods in owner mode to interact with persistent storage (Save, load...)

### Dev requirements and restrictions:
-create method `func saveOwner()-> Bool` ; Firstly encode, then save into local storage.    **to do - discuss API**
-create method `func loadOwner()-> Owner`; Firstly read from local storage, than decode to owner model.
If we unable to read from the local storage, than we should create a new instance of owner.
-create tests.

**Comment by NadzeyaShpakouskaya** [comment]
The issue was closed as unnecessary, the interaction with KeyValueStorage will be done in ViewModel layer.
