### ISSUE TITLE
Allows pet sitter to add information about themself

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#9]
## Depends on tasks:
- #31 
-  #44 
-  #59 
 - #124

## The scope of the current task:
 - #61 
 - #112 
 - #113 
 - #114
- #133 
- #141
- #146 
- #210 

## Description
The goal of this task is to add the ability for pet sitters to add/update their actual information in our app, which will be displayed for pet owners.

### User story:

To tap on the profile button, users can see info about themselves that consists of an avatar, info about the pet sitter, and an `edit` button. 
When this screen appears the first time name is displayed like "User" and other fields will be empty.

When the user presses the `edit` button, the edit pet sitter's information view will be presented.
It contains textfields with the previous information and `Save` button.
If the name textfield will be empty the save button will be disabled and prompt "name is a mandatory field" will be shown.

When the user press `Save` button and the internet connection is lost ( or any errors occur when the request has been sent)  and displays a pop-up window (alert message) with a hint message:
 - text `Your information has not been saved 
 - and 2 buttons: try again(save button) and cancel (exit from editing mode).
When `Try again` button is pressed a new request will be sent to upload the information to the backend. 
When `Cancel` button is pressed, the EditingView will be dismissed and the entered data will not be saved.

If the entered data was successfully sent to the backend, save the entered data in persistent storage.

### Dev requirements and restrictions:

- Create a button to switch between displaying and editing modes. 
- Integrate view into owner main tab view instead of stab. This view is a part of `PetSitterMainTabView`.
- save/load data from the pet sitter to local storage, when the information was successfully loaded to the backend;
- upload data to the backend;

**Comment by NadzeyaShpakouskaya** [comment]
> Saved data doesn't change if the user chooses other screens or close app.
What other screens do you mean, if it will be the single view for the sitter side for now?
If I accidentally switch the tab in the future I will lose all entered information?  

> User can press cancel button to return to the previous screen.
Should we notify the users that they can lose the entered info?

> If connection lost and user press save button display pop up window with hint message(text: you information doesn't save and buttons: try again(save button) and cancel(exit from editing mode)).
If I see the Cancel button I will not assume, that it close the editing mode.
May be message should be like this "Your information couldn't be saved right now. Please check your internet connection." and buttons "Try again" and "Don't save changes"

Do we need these fields right now?
- Change avatar button.
- Location???

We don't have the location information in our model and it would not be preferred from the backend.

**Comment by iBYarchitect** [comment]
@NadzeyaShpakouskaya 
> Should we notify the users that they can lose the entered info?

Having too many notifications can be annoying for users. If you choose to press "cancel," be aware that your data will not be saved. This is a common experience for most users. However, in future releases, we can consider introducing this functionality if users request it.

> If I see the Cancel button I will not assume, that it close the editing mode.
May be message should be like this "Your information couldn't be saved right now. Please check your internet connection." and buttons "Try again" and "Don't save changes"

Here's how I envision this user story: I clicked on the button to edit my personal data. After filling in the fields, I clicked the save button. However, before that, I lost my Internet connection. At this point, a pop-up window appeared notifying me about the connection loss. I had the option to click OK to skip this window. Subsequently, I could choose to click the cancel button and discard the changes made to the fields. Alternatively, I again could click the save button again and receive an error message regarding the Internet connection but if the connection is restored, the data will be saved.
