### ISSUE TITLE
Add the ability to copy text from a card view sitter or owner or any other screen 

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#90]
## Depends on tasks:
- #16
- #70 

## Description
The main goal of the issue is to add the ability for user to copy text from a card view sitter or owner or any other screen

### User story:
User should be able to select text from every text field.

**Comment by NadzeyaShpakouskaya** [comment]
Already has been implemented https://github.com/ios-course/ironfoudation-team-project/pull/134
