### ISSUE TITLE
Сurrency display in petsitter's hourly rate

### ISSUE THREAD

**Issue by iBYarchitect** [ios-course/ironfoudation-team-project#97]
## Depends on tasks:
- #_issue
- #_issue

## Description
Users are faced with the fact that the amount does not change, but the currency of the description of the hourly rate changes.

### User story:
ToDo:
First option:
The user sees only one fixed rate, for example in dollars, so the petsitter sets the rate for walking only in dollars
Second option:
The user sees the petsitter's rate recalculated at the current rate (API is needed) with the current currency code for his region, the petsitter also sets the rate in the current currency of the country where he is located ???

**Comment by NadzeyaShpakouskaya** [comment]
Transferred to new project https://github.com/IronFoundation/iOS-Woof/issues/32
